
#define IDH_TOPIC_NACHALNAYA_STRANITSA                                           2
#define IDH_TOPIC_ANNOTATSIYA                                                    6
#define IDH_TOPIC_SODERZHANIE                                                    7
#define IDH_TOPIC_1__VVEDENIE                                                    8
#define IDH_TOPIC_1_1__OBLAST_PRIMENENIYA                                        9
#define IDH_TOPIC_1_2__KRATKOE_OPISANIE_VOZMOZHNOSTEJ                            10
#define IDH_TOPIC_1_3__UROVEN_PODGOTOVKI_POLZOVATELYA                            11
#define IDH_TOPIC_1_4__PERECHEN_EHKSPLUATATSIONNOJ_DOKUMENTATSII                 12
#define IDH_TOPIC_2__NAZNACHENIE_I_USLOVIYA_PRIMENENIYA                          13
#define IDH_TOPIC_3__PODGOTOVKA_K_RABOTE                                         14
#define IDH_TOPIC_3_1__SOSTAV_I_SODERZHANIE_DISTRIBUTIVNOGO_NOSITELYA_DANNYKH    15
#define IDH_TOPIC_3_2__PORYADOK_ZAGRUZKI_DANNYKH_I_PROGRAMM                      16
#define IDH_TOPIC_3_3__PORYADOK_PROVERKI_RABOTOSPOSOBNOSTI                       17
#define IDH_TOPIC_4__OPISANIE_OPERATSIJ                                          18
#define IDH_TOPIC_GLAVNOE_OKNO                                                   252
#define IDH_TOPIC_OKNO_VYCHISLENIJ                                               262
#define IDH_TOPIC_OKNO_RABOTA_S_DATAMI                                           318
#define IDH_TOPIC_OKNO_RABOTA_SO_SISTEMAMI_SCHISLENIYA                           690
#define IDH_TOPIC_OKNO_RABOTA_S_FIZ__VELICHINAMI                                 309
#define IDH_TOPIC_5__AVARIJNYE_SITUATSII                                         19
#define IDH_TOPIC_6__REKOMENDATSII_PO_OSVOENIYU                                  20
#define IDH_TOPIC_7__TERMINY_I_SOKRASHCHENIYA                                    21
#define IDH_CONTROL_SPISOK_DEJSTVIJ__1                                           253
#define IDH_CONTROL_KNOPKA__POMOSHCH_                                            259
#define IDH_CONTROL_SVERNUT_PROGRAMMU                                            260
#define IDH_CONTROL_ZAKRYT_PROGRAMMU                                             261
#define IDH_CONTROL_SPISOK_DEJSTVIJ__2                                           263
#define IDH_CONTROL_VVOD_DANNYKH_1                                               265
#define IDH_CONTROL_VYVOD_REZULTATA_1                                            266
#define IDH_CONTROL_KNOPKA_C                                                     267
#define IDH_CONTROL_KNOPKA_X                                                     269
#define IDH_CONTROL_KNOPKA_KH_                                                   271
#define IDH_CONTROL_KNOPKA_SIN_X_                                                273
#define IDH_CONTROL_KNOPKA_1_X                                                   275
#define IDH_CONTROL_KNOPKA___1                                                   277
#define IDH_CONTROL_KNOPKA_N_                                                    279
#define IDH_CONTROL_KNOPKA_COS_X_                                                281
#define IDH_CONTROL_KNOPKA__X_                                                   283
#define IDH_CONTROL_KNOPKA___2                                                   285
#define IDH_CONTROL_KNOPKA_LOG_X_                                                287
#define IDH_CONTROL_KNOPKA_TG_X_                                                 289
#define IDH_CONTROL_KNOPKA_LN_X_                                                 291
#define IDH_CONTROL_KNOPKA___3                                                   293
#define IDH_CONTROL_KNOPKA__KH                                                   295
#define IDH_CONTROL_KNOPKA_CTG_X_                                                302
#define IDH_CONTROL_KNOPKA_PI                                                    317
#define IDH_CONTROL__NE_ZABYT___NAZVANIE_KONTROLA_                               400
#define IDH_CONTROL_SPISOK_DEJSTVIJ__3                                           319
#define IDH_CONTROL_VYBOR_NACHALNOJ_DATY                                         324
#define IDH_CONTROL_VYBOR_KONECHNOJ_DATY                                         420
#define IDH_CONTROL_REZULTAT_VYCHISLENIJ                                         522
#define IDH_CONTROL_SPISOK_DEJSTVIYA                                             691
#define IDH_CONTROL_VVOD_DANNYKH_2                                               693
#define IDH_CONTROL_VYVOD_REZULTATA_2                                            694
#define IDH_CONTROL_REDAKTIRUEMYJ_TEKST_3                                        697
#define IDH_CONTROL_REDAKTIRUEMYJ_TEKST_4                                        698
#define IDH_CONTROL_SPISOK_DEJSTVIJ                                              310
#define IDH_CONTROL_SPISOK_IZMERENIJ_                                            312