
#define IDH_TOPIC_NACHALNAYA_STRANITSA                                           2
#define IDH_TOPIC_ANNOTATSIYA                                                    7
#define IDH_TOPIC_SODERZHANIE                                                    8
#define IDH_TOPIC_1__VVEDENIE                                                    9
#define IDH_TOPIC_1_1__OBLAST_PRIMENENIYA                                        10
#define IDH_TOPIC_1_2__KRATKOE_OPISANIE_VOZMOZHNOSTEJ                            11
#define IDH_TOPIC_1_3__UROVEN_PODGOTOVKI_POLZOVATELYA                            12
#define IDH_TOPIC_1_4__PERECHEN_EHKSPLUATATSIONNOJ_DOKUMENTATSII                 13
#define IDH_TOPIC_2__NAZNACHENIE_I_USLOVIYA_PRIMENENIYA                          14
#define IDH_TOPIC_3__PODGOTOVKA_K_RABOTE                                         15
#define IDH_TOPIC_3_1__SOSTAV_I_SODERZHANIE_DISTRIBUTIVNOGO_NOSITELYA_DANNYKH    16
#define IDH_TOPIC_3_2__PORYADOK_ZAGRUZKI_DANNYKH_I_PROGRAMM                      17
#define IDH_TOPIC_3_3__PORYADOK_PROVERKI_RABOTOSPOSOBNOSTI                       18
#define IDH_TOPIC_4__OPISANIE_OPERATSIJ                                          19
#define IDH_TOPIC_GLAVNOE_OKNO                                                   20
#define IDH_TOPIC_OKNO_VYCHISLENIJ                                               21
#define IDH_TOPIC_OKNO_RABOTA_S_DATAMI                                           22
#define IDH_TOPIC_OKNO_RABOTA_SO_SISTEMAMI_SCHISLENIYA                           23
#define IDH_TOPIC_OKNO_RABOTA_S_FIZ__VELICHINAMI                                 28
#define IDH_TOPIC_5__AVARIJNYE_SITUATSII                                         25
#define IDH_TOPIC_6__REKOMENDATSII_PO_OSVOENIYU                                  26
#define IDH_TOPIC_7__TERMINY_I_SOKRASHCHENIYA                                    27
#define IDH_CONTROL_SPISOK_DEJSTVIJ_                                             29
#define IDH_CONTROL_SPISOK_VELICHIN_                                             31
#define IDH_CONTROL_VVOD_ISKHODNOJ_VELICHINY                                     33
#define IDH_CONTROL_VYVOD_REZULTATA                                              34
#define IDH_CONTROL_VYBOR_NACHALNOJ_VELICHINY                                    35
#define IDH_CONTROL_VYBOR_KONECHNOJ_VELICHINY                                    36